version: '3.8'
services:
  lambda-build:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: nutrition-lambda:latest
    environment:
      - DOCKER_BUILDKIT=0  # Disable BuildKit to avoid attestations
