"""Add meal_date column

Revision ID: 4d3a9b1e7573
Revises: a759dd0d5ff2
Create Date: 2025-06-25 11:09:49.709826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3a9b1e7573'
down_revision: Union[str, None] = 'a759dd0d5ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('meal_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'meal_date')
    # ### end Alembic commands ###
